import type { PosterPreset } from "./types";

export const IWD_PRESET: PosterPreset = {
  id: "iwd",
  title: "IWD Poster Creator",
  subtitle: "International Women's Day campaign",
  mainLabel: "Main Portrait",
  mainSublabel: "Central focus - Full color",
  floatingSectionLabel: "Floating Images - auto-converted to B&W",
  enableFloaters: true,
  mainGrayscaleLabel: "Main Portrait B&W",
  overlayPath: "/all.png",
  floatingPositions: [
    { label: "Top Left", x: 240, y: 400, width: 900, height: 1100 },
    { label: "Bottom Right", x: 1650, y: 2000, width: 880, height: 1100 },
    { label: "Bottom Left", x: 240, y: 2300, width: 750, height: 750 },
  ],
  exportFilePrefix: "iwd-poster",
};

export const WHITE_COAT_PRESET: PosterPreset = {
  id: "white-coat-ceremony",
  title: "White Coat Ceremony Creator",
  subtitle: "Induction and recognition poster",
  mainLabel: "Main Portrait",
  mainSublabel: "Ceremony focal portrait",
  floatingSectionLabel: "No floating images for this template",
  enableFloaters: false,
  mainGrayscaleLabel: "Main Portrait B&W",
  overlayPath: "/WCC.png",
  floatingPositions: [
    { label: "Top Right", x: 1800, y: 320, width: 880, height: 1020 },
    { label: "Bottom Left", x: 260, y: 1880, width: 940, height: 1120 },
    { label: "Center Accent", x: 1140, y: 2380, width: 700, height: 760 },
  ],
  nameOverlay: {
    enabled: true,
    fontCssVariable: "--font-funnel",
    color: "#FFFFFF",
    y: 3250,
    fontSize: 110,
    surnameWeight: 800,
    otherWeight: 400,
  },
  exportFilePrefix: "white-coat-poster",
};

export const BIRTHDAY_PRESET: PosterPreset = {
  id: "birthday",
  canvasWidth: 3000,
  canvasHeight: 3000,
  title: "Birthday Poster Creator",
  subtitle: "Drop photo in the frame and add celebrant details",
  mainLabel: "Celebrant Photo",
  mainSublabel: "Placed inside the green frame area",
  floatingSectionLabel: "No floating images for this template",
  enableFloaters: false,
  mainGrayscaleLabel: "Main Photo B&W",
  overlayPath: "/bd.png",
  // rotationDeg lets you tilt the celebrant photo inside the frame.
  mainImagePlacement: { x: 315, y: 950, width: 1080, height: 1080, rotationDeg: 6 },
  floatingPositions: [
    { label: "Unused", x: 0, y: 0, width: 1, height: 1 },
    { label: "Unused", x: 0, y: 0, width: 1, height: 1 },
    { label: "Unused", x: 0, y: 0, width: 1, height: 1 },
  ],
  birthdayOverlay: {
    enabled: true,
    fontCssVariable: "--font-funnel",
    color: "#FFFFFF",
    accentColor: "#F7CC48",
    nameColor: "#FFFFFF",
    nameX: 2140,
    nameY: 2000,
    statusY: 2100,
    statusColor: "#F7CC48",
    dateX: 1350,
    dateY: 2133,
    dateColor: "#370000",
    nameFontSize: 98,
    statusFontSize: 60,
    dateFontSize: 64,
    nameWeight: 700,
    detailWeight: 400,
    surnameWeight: 900,
    otherNameWeight: 400,
    statusWeight: 400,
    dayWeight: 400,
    monthWeight: 900,
  },
  exportFilePrefix: "birthday-poster",
};

